import os
import pandas as pd
from datetime import datetime
from django.shortcuts import render
from django.http import HttpRequest
from django.conf import settings

def home(request):
    """Renders the home page with NBA projections."""
    assert isinstance(request, HttpRequest)
    
    # 1. POINT TO THE EXACT FILE FROM YOUR R SCRIPT
    # Your R script saves to: NBAWeb/NBAWeb/data_feed/projections.csv
    # BASE_DIR is the outer folder, so we join 'NBAWeb', 'data_feed', 'projections.csv'
    csv_path = os.path.join(settings.BASE_DIR, 'NBAWeb', 'data_feed', 'projections.csv')

    context = {
        'title': 'NBA Projections',
        'year': datetime.now().year,
        'projections': [], 
        'error': None
    }

    # 2. READ THE DATA
    if os.path.exists(csv_path):
        try:
            # Read the CSV generated by R
            df = pd.read_csv(csv_path)
            
            # Fill NaN values to avoid HTML errors
            df = df.fillna('')
            
            # Convert to a list of dictionaries for the template
            # resulting list looks like: [{'athlete_display_name': 'LeBron', 'Proj_PTS': 25.4, ...}, ...]
            context['projections'] = df.to_dict('records')
            
        except Exception as e:
            context['error'] = f"Error reading CSV file: {str(e)}"
    else:
        # If the file doesn't exist, tell the user to run the R script
        context['error'] = f"Data file not found at: {csv_path}. Please run your R script first!"

    return render(request, 'index.html', context)

# ... (Keep your contact and about functions the same) ...
def contact(request):
    assert isinstance(request, HttpRequest)
    return render(request, 'app/contact.html', {'title':'Contact', 'year':datetime.now().year})

def about(request):
    assert isinstance(request, HttpRequest)
    return render(request, 'app/about.html', {'title':'About', 'year':datetime.now().year})